FROM python:3.12.6-slim-bookworm

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY backend/worker/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt watchfiles

COPY backend/worker/. .

CMD ["watchfiles", "--filter", "python", "python main.py", "."]
